local Keys = {
    ["ESC"] = 322,
    ["F1"] = 288,
    ["F2"] = 289,
    ["F3"] = 170,
    ["F5"] = 166,
    ["F6"] = 167,
    ["F7"] = 168,
    ["F8"] = 169,
    ["F9"] = 56,
    ["F10"] = 57,
    ["~"] = 243,
    ["1"] = 157,
    ["2"] = 158,
    ["3"] = 160,
    ["4"] = 164,
    ["5"] = 165,
    ["6"] = 159,
    ["7"] = 161,
    ["8"] = 162,
    ["9"] = 163,
    ["-"] = 84,
    ["="] = 83,
    ["BACKSPACE"] = 177,
    ["TAB"] = 37,
    ["Q"] = 44,
    ["W"] = 32,
    ["E"] = 38,
    ["R"] = 45,
    ["T"] = 245,
    ["Y"] = 246,
    ["U"] = 303,
    ["P"] = 199,
    ["["] = 39,
    ["]"] = 40,
    ["ENTER"] = 18,
    ["CAPS"] = 137,
    ["A"] = 34,
    ["S"] = 8,
    ["D"] = 9,
    ["F"] = 23,
    ["G"] = 47,
    ["H"] = 74,
    ["K"] = 311,
    ["L"] = 182,
    ["LEFTSHIFT"] = 21,
    ["Z"] = 20,
    ["X"] = 73,
    ["C"] = 26,
    ["V"] = 0,
    ["B"] = 29,
    ["N"] = 249,
    ["M"] = 244,
    [","] = 82,
    ["."] = 81,
    ["-"] = 84,
    ["LEFTCTRL"] = 36,
    ["LEFTALT"] = 19,
    ["SPACE"] = 22,
    ["RIGHTCTRL"] = 70,
    ["HOME"] = 213,
    ["PAGEUP"] = 10,
    ["PAGEDOWN"] = 11,
    ["DELETE"] = 178,
    ["LEFT"] = 174,
    ["RIGHT"] = 175,
    ["TOP"] = 27,
    ["DOWN"] = 173,
    ["NENTER"] = 201,
    ["N4"] = 108,
    ["N5"] = 60,
    ["N6"] = 107,
    ["N+"] = 96,
    ["N-"] = 97,
    ["N7"] = 117,
    ["N8"] = 61,
    ["N9"] = 118
}

Config = {}
Config.DrawDistance = 2.0
Config.MarkerSize = { x = 1.5, y = 1.5, z = 1.0 }

Config.Shops = {
    {
        id = 1,
        coords = vector3(25.81, -1345.25, 29.5),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 2,
        coords = vector3(-47.29, -1756.7, 29.42),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },

        }
    },
    {
        id = 3,
        coords = vector3(-707.32, -912.9, 19.22),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 4,
        coords = vector3(-707.32, -912.9, 19.22),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 5,
        coords = vector3(1163.39, -322.21, 69.21),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 6,
        coords = vector3(373.59, 325.52, 103.57),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 7,
        coords = vector3(-1821.45, 793.84, 138.11),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 8,
        coords = vector3(-3038.78, 585.85, 7.91),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 9,
        coords = vector3(-3038.78, 585.85, 7.91),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 10,
        coords = vector3(-3241.54, 1001.14, 12.83),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 11,
        coords = vector3(547.77, 2671.75, 42.16),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 12,
        coords = vector3(2679.15, 3280.13, 55.24),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 13,
        coords = vector3(1961.42, 3740.09, 32.34),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 14,
        coords = vector3(22.06, -1106.77, 29.8),
        type = 'weapon',
        hidden = false,
        items = {
            { name = 'WEAPON_PISTOL', label = 'Pistolet', type = 'item_weapon', maxStock = 100, price = 1500, need_license = true, license = 'weapon', ammo = 50 },
            { name = 'WEAPON_MUSKET', label = 'Fusil de chasse', type = 'item_weapon', maxStock = 100, price = 1950, need_license = true, license = 'hunt', ammo = 50 },
            { name = 'WEAPON_KNIFE', label = 'Couteau', type = 'item_weapon', maxStock = 100, price = 100 },
            { name = 'WEAPON_KNUCKLE', label = 'Poing americain', type = 'item_weapon', maxStock = 100, price = 100 },
            { name = 'WEAPON_FLASHLIGHT', label = 'Lampe torche', type = 'item_weapon', maxStock = 100, price = 100 },
            { name = 'pistol_clip', label = 'Chargeur pistolet', type = 'item_standard', maxStock = 100000, price = 200 },
            { name = 'sniper_clip', label = 'Balle de fusil de chasse / sniper', type = 'item_standard', maxStock = 100000, price = 5 },
        }
    },
    {
        id = 15,
        coords = vector3(-652.79,  -1757.19, 24.58),
        type = 'illegal',
        hidden = true,
        items = {
            { name = 'lockpick', label = 'Outil de crochetage', type = 'item_standard', maxStock = 100000, price = 5000 },
            { name = 'hackerDevice', label = 'Outil de hacker', type = 'item_standard', maxStock = 100000, price = 10000 },
            { name = 'hammerwirecutter', label = 'Coupe-fil', type = 'item_standard', maxStock = 100000, price = 5000 },
            { name = 'accesscard', label = 'Carte d\'accès', type = 'item_standard', maxStock = 100000, price = 10000 },
            { name = 'rifle_clip_unmarked', label = 'Chargeur de fusil d\'assault intraçable', type = 'item_standard', maxStock = 100000, price = 70000 },
            { name = 'pistol_clip_unmarked', label = 'Chargeur de pistolet intraçable', type = 'item_standard', maxStock = 100000, price = 50000 },
            { name = 'shotgun_clip_unmarked', label = 'Chargeur de fusil à pompe intraçable', type = 'item_standard', maxStock = 100000, price = 70000 },
            { name = 'weapon_suppressor', label = 'Silencieux', type = 'item_standard', maxStock = 100000, price = 25000 },
            { name = 'weapon_clip_extended', label = 'Chargeur étendu', type = 'item_standard', maxStock = 100000, price = 35000 },
            { name = 'armor', label = 'Gilet par balle', type = 'item_standard', maxStock = 100000, price = 35000 },
            { name = 'WEAPON_PISTOL', label = 'Pistolet', type = 'item_weapon', maxStock = 100, price = 3000, ammo = 50 },
            { name = 'WEAPON_MUSKET', label = 'Fusil de chasse', type = 'item_weapon', maxStock = 100, price = 3900, ammo = 50 },
            { name = 'pistol_clip', label = 'Chargeur pistolet', type = 'item_standard', maxStock = 100000, price = 100 },
            { name = 'sniper_clip', label = 'Balle de fusil de chasse / sniper', type = 'item_standard', maxStock = 100000, price = 5 }
        }
    },
    {
        id = 16,
        coords = vector3(46.40, -1749.70, 29.63),
        type = 'others',
        hidden = false,
        items = {
            { name = 'scissors', label = 'Ciseaux', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'drill', label = 'Perceuse', type = 'item_standard', maxStock = 100000, price = 300 },
            { name = 'animal_bait', label = 'Appat de chasse', type = 'item_standard', maxStock = 100000, price = 50},
            { name = 'demineralized_water', label = 'Eau demineralisée', type = 'item_standard', maxStock = 100000, price = 50 },
            { name = 'scale', label = 'Balance de précision', type = 'item_standard', maxStock = 100000, price = 300 },
            { name = 'screwdriver', label = 'Tournevis', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'click_wrench', label = 'Clé a Cliquet', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'adjustable_wrench', label = 'Clé à molette', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'torque_wrench', label = 'Clé dynamo', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'WEAPON_GOLFCLUB', label = 'Club de golf', type = 'item_weapon', maxStock = 100000, price = 50 },
            { name = 'WEAPON_BAT', label = 'Batte de baseball', type = 'item_weapon', maxStock = 100000, price = 50 },
            { name = 'fixkit', label = 'Kit de réparation', type = 'item_standard', maxStock = 50, price = 300 },
            { name = 'WEAPON_CROWBAR', label = 'Pied de biche', type = 'item_weapon', maxStock = 100000, price = 1000 },
            { name = 'WEAPON_WRENCH', label = 'Clé anglaise', type = 'item_weapon', maxStock = 100000, price = 1000 },
            { name = 'WEAPON_FIREEXTINGUISHER', label = 'Extincteur', type = 'item_weapon', maxStock = 100000, price = 50 },
            { name = 'WEAPON_HATCHET', label = 'Hache', type = 'item_weapon', maxStock = 100000, price = 1000 },
            { name = 'WEAPON_HAMMER', label = 'Marteau', type = 'item_weapon', maxStock = 100000, price = 1000 },
            { name = 'tissu_bag', label = 'Sac en tissu', type = 'item_standard', maxStock = 100, price = 1 },
            { name = 'glass_bottle', label = 'Bouteille en verre', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'recycled_plastic', label = 'Plastique recyclé', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'recycled_boxes', label = 'Carton recyclé', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'fishingrod', label = 'Canne à pêche', type = 'item_standard', maxStock = 100000, price = 100 },
            { name = 'fishbait', label = 'Appat de pêche', type = 'item_standard', maxStock = 100000, price = 1},
            { name = 'contract', label = 'Acte de vente véhicule', type = 'item_standard', maxStock = 100000, price = 1},
            { name = 'spray_remover', label = 'éponge', type = 'item_standard', maxStock = 100000, price = 20},
            { name = 'spray', label = 'Bombe de peinture', type = 'item_standard', maxStock = 100000, price = 250},
            { name = 'ocb_paper', label = 'Feuilles OCB', type = 'item_standard', maxStock = 10000, price = 5 },
            { name = 'lighter', label = 'Briquet', type = 'item_standard', maxStock = 100000, price = 3 },
            { name = 'woods_plank', label = 'Planche en bois', type = 'item_standard', maxStock = 100000, price = 10},
            { name = 'binoculars', label = 'Jumelles', type = 'item_standard', maxStock = 100000, price = 10},
        }
    },
    {
        id = 17,
        coords = vector3(962.19, -2189.44, 30.51),
        type = 'hunt',
        hidden = false,
        jobBuy = { 'ravenbutchery', 'atomburger' },
        items = {
            { name = 'meat_carcass', label = 'Carcasse de viande', type = 'item_standard', maxStock = 100, price = 20 },
            { name = 'steack', label = 'Steack', type = 'item_standard', maxStock = 100, price = 5 },
        }
    },
    {
        id = 18,
        coords = vector3(148.36, -232.49, 54.42),
        type = 'apple',
        hidden = false,
        items = {
            { name = 'phone', label = 'Téléphone', type = 'item_standard', maxStock = 100000, price = 550 }
        }
    },
    {
        id = 19,
        coords = vector3(264.77, -747.84, 30.83),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 10000, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    },
    {
        id = 20,
        coords = vector3(412.87, 6538.93, 27.73),
        type = 'ferm',
        hidden = false,
        jobBuy = { 'bakery', 'atomburger', 'brewer' },
        items = {
            { name = 'potatoes_bag', label = 'Sac de pomme de terre', type = 'item_standard', maxStock = 50, price = 10 },
            { name = 'flour_bag', label = 'Sac de farine', type = 'item_standard', maxStock = 50, price = 10 },
            { name = 'ognions', label = 'Oignons', type = 'item_standard', maxStock = 50, price = 1 },
            { name = 'clean_tomato', label = 'Tomate', type = 'item_standard', maxStock = 50, price = 1 },
            { name = 'clean_salad', label = 'Salade', type = 'item_standard', maxStock = 50, price = 1 },
        }
    },
    {
        id = 21,
        coords = vector3(-121.45, 6204.69, 32.38),
        type = 'chicken',
        hidden = false,
        jobBuy = { 'bakery', 'atomburger' },
        items = {
            { name = 'chicken_breast', label = 'Filet de poulet', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'chicken_wings', label = 'Aile de poulet', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'chicken_tenders', label = 'Tenders de poulet', type = 'item_standard', maxStock = 50, price = 5 },
        }
    },
    {
        id = 22,
        coords = vector3(424.55, 5614.08, 766),
        type = 'parachute',
        hidden = false,
        items = {
            { name = 'GADGET_PARACHUTE', label = 'Parachute', type = 'item_weapon', maxStock = 100000, price = 3000},
        }
    },
    {
        id = 23,
        coords = vector3( 1729.79,6416.28,35.04),
        type = 'shop',
        hidden = false,
        items = {
            { name = 'orange_juice_bottle', label = 'Bouteille de jus d\'orange', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'apple_juice_bottle', label = 'Bouteille de jus de pomme', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'eggs_boxe', label = 'Boite d\'oeufs', type = 'item_standard', maxStock = 50, price = 5 },
            { name = 'milk_bottle', label = 'Bouteille de lait', type = 'item_standard', maxStock = 20, price = 30 },
            { name = 'grape_juice_bottle', label = 'Bouteille de jus de raisins', type = 'item_standard', maxStock = 20, price = 65 },
            { name = 'red_wine_bottle', label = 'Bouteille de vin rouge', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'white_wine_bottle', label = 'Bouteille de vin blanc', type = 'item_standard', maxStock = 5, price = 130 },
            { name = 'champagne_bottle', label = 'Bouteille de champagne', type = 'item_standard', maxStock = 5, price = 450 },
            { name = 'aop_wine_bottle', label = 'Bouteille de grand cru', type = 'item_standard', maxStock = 5, price = 250 },
            { name = 'atom_wings', label = 'Atom wings', type = 'item_standard', maxStock = 50, price = 30 },
            { name = 'atom_burger_cheese', label = 'Atom cheese burger', type = 'item_standard', maxStock = 50, price = 70 },
            { name = 'donut', label = 'Donut', type = 'item_standard', maxStock = 20, price = 40 },
            { name = 'chicken_sandwich', label = 'Sandwich au poulet', type = 'item_standard', maxStock = 10, price = 100 },
            { name = 'water', label = 'Eau', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'energy_drink', label = 'Redbull', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'cola', label = 'Coca-cola', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'lemonade', label = 'Limonade', type = 'item_standard', maxStock = 100000, price = 10 },
            { name = 'chocolate', label = 'Chocolat', type = 'item_standard', maxStock = 100000, price = 5 },
            { name = 'rhum_bottle', label = 'Bouteille de rhum', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'beer', label = 'Bouteille de bière', type = 'item_standard', maxStock = 50, price = 20 },
            { name = 'whisky_bottle', label = 'Bouteille de whisky', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'vodka_bottle', label = 'Bouteille de vodka', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'tequila_bottle', label = 'Bouteille de tequila', type = 'item_standard', maxStock = 10, price = 200 },
            { name = 'ice', label = 'Glacons', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'mint', label = 'menthe', type = 'item_standard', maxStock = 100000, price = 2 },
            { name = 'malbora', label = 'Malbora', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'gitanes', label = 'Gitanes', type = 'item_standard', maxStock = 30, price = 40 },
            { name = 'cigar', label = 'Cigare', type = 'item_standard', maxStock = 10000, price = 90 },
        }
    }
}

